spring.application.name=greeting-service
server.port=8080

greeting-service.greeting=Ola
greeting-service.default-name=Mundo

spring.profiles.active=fr


management.endpoint.env.show-values=always

spring.config.import=optional:configserver:http://localhost:8888\
  
eureka.client.service-url.default-zone=http://localhost:8781/eureka

eureka.instance.prefer-ip-address=true

eureka.instance.instance-id=${spring.application.name}:${server.port}

eureka.client.healthcheck.enabled=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.description=Microservice Java 2026
info.app.autor=Kauê Anacleto Saggiorato

eureka.instance.metadata-map.github.repo=KaueSaggiorato/Microservices-Java

management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true